from __future__ import annotations

import hashlib
import re
from typing import TYPE_CHECKING, Protocol

from cc_pushback.models import DedupKey

if TYPE_CHECKING:
    from collections.abc import Iterator, Sequence
    from pathlib import Path

    from cc_transcript.models import TranscriptEvent

    from cc_pushback.models import FeedbackCandidate

__all__ = [
    "ASK_USER_ANSWERED_PREFIX",
    "DENIAL_PREFIX",
    "INTERRUPT_RE",
    "MESSAGE_JUNK_RE",
    "PLAN_APPROVED_PREFIX",
    "USER_SAID_MARKER",
    "USER_SAID_TRAILER",
    "TranscriptSource",
    "dedup_key",
]

DENIAL_PREFIX = "The user doesn't want to proceed with this tool use. The tool use was rejected"
USER_SAID_MARKER = "To tell you how to proceed, the user said:\n"
USER_SAID_TRAILER = "Note: The user's next message"
PLAN_APPROVED_PREFIX = "User has approved your plan"
ASK_USER_ANSWERED_PREFIX = "Your questions have been answered:"
INTERRUPT_RE = re.compile(r"\[Request interrupted by user(?: for tool use)?\]")
MESSAGE_JUNK_RE = re.compile(
    r"<(?:system[_-](?:instruction|reminder)"
    r"|local-command-(?:stdout|caveat)"
    r"|command-(?:name|message|args)"
    r"|task-notification"
    r"|teammate-message"
    r"|scheduled-task"
    r"|persisted-output"
    r"|output-file)\b"
    r"|Caveat: The messages below were generated by the user while running local commands\."
    r"|REMAINING_TASKS_ACKNOWLEDGED"
    r"|<<[a-z][a-z0-9-]*>>"
    r"|^# Augment Agent\b"
    r"|^Base directory for this skill:"
    r"|(?:###\s+[\w][\w \-]{0,30}\s+){3,}###",
    re.IGNORECASE,
)


class TranscriptSource(Protocol):
    """A detector that extracts feedback candidates from one transcript file."""

    def candidates_for_file(
        self, path: Path, events: Sequence[TranscriptEvent]
    ) -> Iterator[FeedbackCandidate]: ...


def dedup_key(*parts: str) -> DedupKey:
    """Returns the stable dedup key for ``parts``.

    Args:
        parts: The content fragments that uniquely identify a candidate.

    Returns:
        The SHA-256 hex digest of the parts joined by a null byte.
    """
    return DedupKey(hashlib.sha256("\x00".join(parts).encode()).hexdigest())
